name: Deploy Basic Tech Website

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use your project's Node.js version
          cache: "npm"

      - name: Install Dependencies
        run: npm install --frozen-lockfile # Change command to pnpm install

      - name: Build Next.js App
        run: npm run build # Change command to pnpm run build

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll # Prevents GitHub Pages from using Jekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Deploy the 'out' directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
